config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "locations#index"

  resources :users, param: :slug
  # routes for editing password
  get "/users/:slug/edit/password_update" => "users#password", as:"password_user"
  patch "/users/:slug/edit/password_update" => "users#password_update"

  # route for log-in screen
  get "/login" => "sessions#new"
  # route for creating new session id
  post "/sessions" => "sessions#create"
  # route to logging out of the session
  get "/logout" => "sessions#destroy"

  resources :posts
  resources :locations, param: :slug

 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/location.rb
class Location < ApplicationRecord
  has_many :posts, dependent: :destroy
  include FriendlyId
  friendly_id :city_country, use: [:finders, :slugged]
  def city_country
  "#{city}-#{country}"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :location, optional: true

  validates_length_of :title, :within => 1..200, :too_long => "Title is too long!", :too_short => "Title is too short!" , allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  has_secure_password

  # Handles the URLS
  include FriendlyId
  friendly_id :first_name_and_last_name, use: [:finders, :slugged]

  # Handles image uploader - the :image is from the schema
  # mount_uploader :image, ImageUploader

  def first_name_and_last_name
  "#{first_name}-#{last_name}"
  end
  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
  end
  def show
    @location = Location.friendly.find(params[:slug])
    @locationposts = @location.posts.order(created_at: :desc).page(params[:page]).per(5)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: [:show]
  before_action :check_owner, only: [:edit, :update, :destroy]
  before_action :find_post, only: [:edit, :show, :update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @user = current_user
    location = params[:location][:city]
    @location = Location.find_by(city: location)
    if @post.save
      @user.posts << @post
      @location.posts << @post
    end
    redirect_to user_path(@user)
  end

  def edit
  end

  def update
    location_params = params[:location][:city]
    @location = Location.find_by(city: location_params)
    @post.update_attributes(post_params)
    # if save - update attributes
    if @post.save
      @post.update_attributes(post_params)
      @post.update_attribute(:location_id, @location.id)
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.messages[:title].join(". ")
      render :edit
    end
  end

  def show
  end

  def destroy
    post_id = params[:id]
    post = Post.find_by_id(post_id)
    post.destroy
    redirect_back(fallback_location: root_path)
  end

  def find_post
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :id, :image)
  end

  def check_owner
    @post = Post.find_by_id(params[:id])
    if session[:user_id].to_s != @post.user.id.to_s
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user.nil?
      @user = User.new
    else
      redirect_to user_path(current_user)
    end

  end
  def create
    @user = User.confirm(login_params)
    if @user
      login(@user)
      flash[:notice] = "Succesfully logged in!"
      redirect_back(fallback_location: user_path(@user))
    else
      flash[:error] = "Login incorrect. Please try again"
      redirect_to login_path
    end
  end
  def destroy
    logout
    flash[:notice] = "Succesfully logged out!"
    redirect_to root_path
  end

  private
  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create, :user_params, :show]
  before_action :check_owner, only: [:edit, :update, :password_update]

  def index
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    login(@user)
    redirect_to user_path(@user)
  end

  def show
    @user = User.friendly.find(params[:slug])
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(5)
  end

  def edit
    @user = User.friendly.find(params[:slug])
  end

  def update
    user = User.find(params[:slug])
    user.update_attributes(user_update_params)
    if user.save
      redirect_to user_path(user)
    end
  end

  def password
    @user = User.friendly.find(params[:slug])
    render :password_update
  end

  def password_update
    user = User.find(params[:slug])
    user.update_attributes(update_password_params)
    if user.save
      flash[:notice] = "Succesfully updated password!"
      redirect_to user_path(user)
    else
      flash[:notice] = "Password not changed, please try again!"
      redirect_back(fallback_location: user_path(user))
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :city, :state, :country, :email, :password, :image)
  end

  def user_update_params
    params.require(:user).permit(:first_name, :last_name, :city, :state, :country, :email, :image)
  end

  def update_password_params
    params.require(:user).permit(:password)
  end

  def check_owner
    if session[:user_id] != User.friendly.find(params[:slug]).id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  def logout
    @current_user = session[:user_id] = nil
  end

  def require_login
    if session[:user_id].nil?
      redirect_to new_user_path
    end
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sign_in.html.erb
<h5>Sign-in</h5>
<div class="sign_in_div">
  <!-- <%= f.label :email, id:'sign_in_form'%> -->
  <%= f.email_field :email, placeholder:"Email"%>
</div>
<div class="sign_in_div">
  <!-- <%= f.label :password, id:'sign_in_form'%> -->
  <%= f.password_field :password, placeholder:"Password", id:'sign_in_form'%>
</div>

app/views/layouts/_user_forms.html.erb
<h5>Take the plunge! Join Vagabond!</h5>
<div>
  <%= f.label :first_name, "First Name"%>
  <%= f.text_field :first_name%>
</div>
<div>
  <%= f.label :last_name, "Last Name"%>
  <%= f.text_field :last_name %>
</div>
<div>
  <%= f.label :city, "City"%>
  <%= f.text_field :city %>
</div>
<div>
  <%= f.label :state, "State"%>
  <%= f.text_field :state %>
</div>
<div>
  <%= f.label :country, "Country"%>
  <%= f.text_field :country %>
</div>
<div>
  <%= f.label :image, "Profile Picture" %>
  <%= f.url_field :image %>
  <!-- <%= f.file_field :image %> -->
</div>
<div>
  <%= f.label :email, "Email"%>
  <%= f.email_field :email %>
</div>
<div>
  <%= f.label :password, "Password"%>
  <%= f.password_field :password%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vagabond</title>
    <!-- Compiled and minified CSS -->

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- navbar begin -->
    <div class="navbar-fixed">

     <nav style="background-color: white; top: 0">
        <div class="nav-wrapper">
          <%= link_to root_path do %>
            <%= image_tag(asset_path("logo_travel_with_us.png"), class:"brand-logo", style: "height: 100%") %>
          <% end %>
            <!-- begin header -->
            <div class="brand-logo valign-wrapper hide-on-med-and-down" style="left: 38%">
              <!-- <div style="position: relative"> -->
              <h4 style="display: inline; color: black; left: 50%">TRAVEL</h4><h1 class="title" style="display: inline; color: black;">with</h1><h4 style="display: inline; color: black;">US</h4>
            <!-- </div> -->
            </div>
            <!-- end header -->
          <a href="#" data-activates="mobile-demo" class="button-collapse right"><i class="material-icons" style="color: black">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a class="dropdown-button" href="#!" data-activates="dropdown1">EXPLORE<i class="material-icons right">arrow_drop_down</i></a></li>
            <% if current_user %>
            <li><%=link_to "PROFILE", user_path(current_user) %></li>
            <li><%=link_to "LOG OUT", logout_path %></li>
            <% else %>
            <li>
              <%=link_to "SIGN UP", href="#sign-up", class:"modal-trigger"%>
            </li>
            <li>
              <%=link_to "LOG IN", href="#sign-in-modal", class:"modal-trigger"%>
            </l1>
            <% end %>
          </ul>
          <ul class="side-nav" id="mobile-demo">
              <li><%=link_to "HOME", root_path %></li>
            <% if current_user %>
              <li><%=link_to "PROFILE", user_path(current_user) %></li>
              <li><%=link_to "LOG OUT", logout_path %></li>
            <% else %>
              <li><%=link_to "SIGN UP", new_user_path %></li>
              <li><%=link_to "LOGIN", login_path %></li>
            <% end %>
              <li><%=link_to "BARCELONA", location_path("barcelona-spain") %></li>
              <li><%=link_to "LONDON", location_path("london-uk") %></li>
              <li><%=link_to "PARIS", location_path("paris-france") %></li>
              <li><%=link_to "ST. PETERSBURG", location_path("st-petersburg-russia") %></li>
          </ul>
        </div>
      </nav>
    </div>
      <!-- navbar end -->

      <!-- Modal Trigger -->
      <div class="modal-for-sign-up">
        <%= form_for (User.new), url:users_path, method: "post" do |f| %>
          <div id="sign-up" class="modal">
            <div class="modal-content">

                <%= render partial: "layouts/user_forms", locals: { f: f } %>
            </div>
          <div class="modal-footer">
        <%= f.submit "Create Account", class: "modal-action modal-close waves-effect waves-green btn-flat" %>
        <% end %>
          </div>
        </div>
      </div>

      <!-- MODAL FOR LOGIN -->
      <%= form_for :user, url: "/sessions", method: "post" do |f| %>
        <div id="sign-in-modal" class="modal">
          <div class="modal-content">
            <%= render partial: "layouts/sign_in", locals: { f: f } %>
          </div>
          <div class="modal-footer">
        <%= f.submit "LOG IN", class: "modal-action modal-close waves-effect waves-green btn-flat", id: "sign-in-button" %>
      <% end %>
        </div>
      </div>

      <!-- BEGIN Post Show Page -->
      <%= stylesheet_link_tag %>
      <%= yield(:head) %>
      <!-- END Post show Page -->
        <div class="col s8 push-s2">
          <% flash.each do |name, msg| %>
           <div id='toast-container'>
             <%= javascript_tag "Materialize.toast('#{msg}', 4000)" %>
           </div>
          <% end %>
        </div>

<ul id="dropdown1" class="dropdown-content" style="margin-top: 64px">
  <li><%=link_to "Barcelona", location_path("barcelona-spain") %></li>
  <li><%=link_to "London", location_path("london-uk") %></li>
  <li><%=link_to "Paris", location_path("paris-france") %></li>
  <li><%=link_to "St. Petersburg", location_path("st-petersburg-russia") %></li>
</ul>
      <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<div class="content" style="position: relative; top: 20px">
  <div class="header">
    <p>Traveling abroad in Europe? Take a tour and discover what there is to offer from travelers just like yourself. Here you will have the ability to see Europe as they saw it through their eyes. Take a peak at all the reviews and enjoy. We can't wait to hear from you next!</p>
  </div>
<!-- BEGIN locations -->

<div class="container-fluid">
  <div class="row valign" style="vertical-align:top">

    <% @locations.each do |location| %>
    <div class="col s12 m6">
      <div class="card" style="background-image: url('<%= asset_path(location.background_image) %>'); border-radius: 0">
        <div class="card-content white-text">
          <span class="title text-shadow"><h3><%= location.city %></h3></span><br>
          <p><span class="text-shadow"><%= location.description %></span></p><br><br>
          <img src="<%= asset_path(location.icon_image) %>" style="width:125px"><br><br><br>
        <%= link_to "DISCOVER #{location.city.upcase}", location_path(location.slug), class: "btn-card text-shadow btn-hover" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
</div>

<!-- END locations -->

app/views/locations/show.html.erb
<div class="parallax-container">
    <div class="parallax">
      <% current_image = @locationposts.sample.image %>
      <% if current_image.nil? %>
        <%= image_tag(@location.background_image, class: 'parallax-img') %>
      <% else %>
        <%= image_tag(current_image, class: 'parallax-img') %>
      <% end %>
      </div>

  </div>
  <div class="section white">
    <div class="row container">
      <h2 class="header title"><%= @location.city %></h2>
      <!-- BEGIN POST data -->
      <% if session[:user_id].nil?  %>
      <% else %>
        <div class="fixed-action-btn">
          <%= link_to new_post_path({:location_id => @location.city}),class: "btn-floating btn-large black" do %>
            <i class="large material-icons">add</i>
          <% end %>
        </div>
      <% end %>
      <% @locationposts.each do |post| %>
        <ul>
          <span class="post-title-color title-height"><%= post.title %></span><br>
          <b>Author: </b><%= link_to "#{post.user.first_name} #{post.user.last_name}", user_path(post.user.slug) %><br>
          <b>Post Date: </b><%= post.created_at.strftime("%B").to_s + " " + post.created_at.day.to_s + ", " + post.created_at.year.to_s %> <br>
          <b>Description: </b><%= post.description.slice(0, 210)+"..." %>
          <% if session[:user_id].nil? || session[:user_id] != post.user.id %>
          <%= link_to "Read More", post_path(post.id) %>
          <hr>
          <% else %>
            <%= link_to "Read More", post_path(post.id) %><br>
            <%= button_to "Edit Post", edit_post_path(post.id), method:'get', class: 'btn btn-inline' %>
            <%= button_to 'Delete', {:controller => "posts", :action => 'show', :id => post.id}, data: {:confirm => "Are you sure you want to delete the #{post.title} post?"}, :method => :delete, class: 'btn btn-2 delete-button' %>
            <hr>
          <% end %>
        </ul>
      <% end %>
      <!-- END POST data -->

      <!-- pagination -->
      <%= paginate @locationposts %>
      <div class="pagination_page_info">
        <%= page_entries_info @locationposts %>
      </div>
    </div>
  </div>

  <div class="parallax-container">
    <div class="parallax">
      <% current_image = @locationposts.sample.image %>
      <% if current_image.nil? %>
        <%= image_tag(@location.background_image, class: 'parallax-img') %>
      <% else %>
        <%= image_tag(current_image, class: 'parallax-img') %>
      <% end %>
    </div>
  </div>

app/views/posts/edit.html.erb
<!--We removed turbolinks  -->
<div class="container">
  <div class="row" style="margin-top: 0.75rem">

    <h3 class="post-title-color">Edit Post</h3>
    <%= form_for @post, method: "patch" do |f| %>
    <div>
      <%= f.label :title%>
      <%= f.text_field :title %>
    </div>
    <div>
      <% if @post.location.city.to_s == "St. Petersburg" %>
      <%= f.label :city%>
      <%= select(:location, :city, [['St. Petersburg', 'St. Petersburg'], ['Paris', 'Paris'], ['London', 'London'], ['Barcelona', 'Barcelona']]) %>
      <% elsif @post.location.city.to_s == "Paris" %>
      <%= f.label :city%>
      <%= select(:location, :city, [['Paris', 'Paris'], ['London', 'London'], ['Barcelona', 'Barcelona'], ['St. Petersburg', 'St. Petersburg']]) %>
      <% elsif @post.location.city.to_s == "London" %>
      <%= f.label :city%>
      <%= select(:location, :city, [['London', 'London'], ['Barcelona', 'Barcelona'], ['St. Petersburg', 'St. Petersburg'], ['Paris', 'Paris']]) %>
      <% else %>
      <%= f.label :city%>
      <%= select(:location, :city, [['Barcelona', 'Barcelona'], ['St. Petersburg', 'St. Petersburg'], ['Paris', 'Paris'], ['London', 'London']]) %>
      <% end %>
    </div>
    <div>
      <%= f.label :image%>
      <%= f.url_field :image %>
    </div>
    <div>
      <%= f.label :description%>
      <%= f.text_field :description %>
    </div>
    <%= f.submit "Save Changes", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row" style="margin-top: 0.75rem">
    <h3 class="post-title-color">Create a post</h3>
    <%= form_for @post do |f| %>
    <div>
      Title: <%= f.text_field :title %>
    </div>
    <div>
      Photo: <%= f.url_field :image %>
    </div>
    <div>
      <% if params[:location_id] == "St. Petersburg" %>
      City:<%= select(:location, :city, [['St. Petersburg', 'St. Petersburg'], ['Paris', 'Paris'], ['London', 'London'], ['Barcelona', 'Barcelona']]) %>
      <% elsif params[:location_id] == "Paris" %>
      City:<%= select(:location, :city, [['Paris', 'Paris'], ['London', 'London'], ['Barcelona', 'Barcelona'], ['St. Petersburg', 'St. Petersburg']]) %>
      <% elsif params[:location_id] == "London" %>
      City:<%= select(:location, :city, [['London', 'London'], ['Barcelona', 'Barcelona'], ['St. Petersburg', 'St. Petersburg'], ['Paris', 'Paris']]) %>
      <% else %>
      City:<%= select(:location, :city, [['Barcelona', 'Barcelona'], ['St. Petersburg', 'St. Petersburg'], ['Paris', 'Paris'], ['London', 'London']]) %>
      <% end %>
    </div>
    <div>
      Description: <%= f.text_field :description %>
    </div>
    <%= f.submit "Create Post", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :head do %>
  <style>
    body {
      background-color: black;
    }
  </style>
<% end %>
<div class="container">
  <div class="row post-show-wht z-depth-5 post-margin" >
    <div class="col s12">
      <h3 class="title post-title-color"><%= @post.title %></h3>
      <hr>
      <div class="row" >
        <!-- BEGIN IMAGE FOR INDIVIDUAL POST -->
        <div class="col s12 m3">
          <% if @post.image.nil? %>
          <%= image_tag(asset_path('no_image.png'), class: "post-image z-depth-4") %><br>
          <% else %>
          <%= image_tag(@post.image, class: "post-image z-depth-4") %><br>
          <% end %>
          <!-- BEGIN BUTTONS -->
          <%= link_to "Back", :back , class: "btn btn-post" %>
          <% if session[:user_id].nil? || session[:user_id] != @post.user.id %>
          <% else %>
            <%= link_to "Edit Post", edit_post_path(@post.id), class: "btn btn-post" %>
            <% end %>
          </div>
          <!-- END BUTTONS -->
          <!-- END IMAGE FOR INDIVIDUAL POST -->
          <!-- BEGIN POST CONTENT -->
          <div class="col s12 m9">
            <b>Location: </b><%= @post.location.city %> <br>
            <b>Author: </b><%= link_to "#{@post.user.first_name} #{@post.user.last_name}", user_path(@post.user.slug) %> <br>
            <b>Description: </b><%= @post.description %> <br>
          </div>
          <!-- END POST CONTENT -->
        </div>
      </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row" style="margin-top: 0.75rem">
      <h3>Hello <span class="post-title-color"><%= @user.first_name %></span></h3>
      <p>Keep us up to date with your current information</p>
      <%= form_for @user do |f| %>
      <div>
        <%= f.label :first_name%>
        <%= f.text_field :first_name %>
      </div>
      <div>
        <%= f.label :last_name%>
        <%= f.text_field :last_name %>
      </div>
      <div>
        <%= f.label :city%>
        <%= f.text_field :city %>
      </div>
      <div>
        <%= f.label :state%>
        <%= f.text_field :state %>
      </div>
      <div>
        <%= f.label :country%>
        <%= f.text_field :country %>
      </div>
      <div>
        <%= f.label :image%>
        <%= f.url_field :image %>
      </div>
      <div>
        <%= f.label :email%>
        <%= f.email_field :email %>
      </div>
      <div class="btn-inline">
      <%= f.submit "Save Changes", class: "btn" %>
      <% end %>
     </div>
     <%= link_to "Change Password", password_user_path(@user.slug), class: "btn btn-red right" %>
   </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col s8 push-s2">
    <br>
    <%= form_for @user do |f| %>
      <%= render partial: "layouts/user_forms", locals: { f: f } %>
    <%= f.submit "Create Account", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/users/password_update.html.erb
<div class="container">
<div class="row" style="margin-top: 0.75rem">
  <div class="push-s2">
    <h3 style="display: inline">Hello </h3><h3 class="post-title-color" style="display: inline"><%= @user.first_name %></h3>
    <p>Update Password</p>
    <%= form_for @user, :url => url_for(:controller => 'users', :action => 'password_update'), method: "patch" do |f| %>
    <div>
      <%= f.label :password%>
      <%= f.password_field :password %>
    </div>
    <%= f.submit "Change Password", class: "btn" %>
    <% end %>
   </div>
 </div>
 </div>

app/views/users/show.html.erb
<div id="bg" class="container-fluid" style="background-image: url(
  <% if @user.posts.empty? %>
    <%= asset_path('europe_background_no_image.jpg') %>
    <% else %>
      <% current_back_ground_image = @user.posts.sample.image %>
        <% if current_back_ground_image.empty? %>
          <%= asset_path('europe_background_no_image.jpg') %>
        <% else %>
          <%= current_back_ground_image %>
        <% end %>
  <% end %>);">

  <!-- BEGIN Profile image and description -->
  <!-- BEGIN Profile IMAGE -->
  <div class="row prof-image">

    <% if @user.image.empty? %>
      <%= image_tag(asset_path('default_user_no_image.png'), class: "circle") %>
    <% else %>
      <%= image_tag(@user.image, class: "circle") %>
    <% end %>
  </div>
  <!-- END Profile IMAGE -->
  <!-- BEG COTNAINER FOR CONTENT -->
    <div class="container">
    <div class="row" style="margin-bottom: 0px">
      <div class="col s12 wht-cont z-depth-5">
          <!-- BEGIN PROFILE INFO -->
          <div class="prof-description">
            <h4><%= @user.first_name.upcase %> <%= @user.last_name.upcase %></h4>
            <p><b>location: </b><%= @user.city %><br>
            <b>Date Joined: </b><%= @user.created_at.strftime("%B").to_s + " " + @user.created_at.year.to_s %></p>
          </div>
          <!-- END PROFILE INFO -->
          <!-- BEGIN profile buttons -->
          <% if session[:user_id].nil? || session[:user_id] != @user.id %>
          <% else %>
            <%= link_to "Edit Profile", edit_user_path(@user.slug), class: "btn" %>

          <% end %>
          <div class="post-content">
            <h3 class="post-title title">POSTS</h3>
          </div>
          <hr>
          <!-- END profile buttons -->
          <!-- BEGIN POST DATA -->
              <% @posts.each do |post| %>
                <div class="row">
                  <!-- BEGIN IMAGE FOR POST -->
                  <br>
                  <div class="col s12 m3">
                    <% if post.image.empty?  %>
                      <%= image_tag(asset_path('no_image.png'), class: "post-image z-depth-4") %>
                    <% else %>
                      <%= image_tag(post.image, class: "post-image z-depth-4") %>
                    <% end %>
                    <br>
                    <% if session[:user_id].nil? || session[:user_id] != @user.id %>
                    <% else %>
                      <%= link_to "Edit Post", edit_post_path(post.id), class: "btn btn-post" %>
                      <%= button_to 'Delete', {:controller => "posts", :action => 'show', :id => post.id}, data: {:confirm => "Are you sure you want to delete the #{post.title} post?"}, :method => :delete, class: 'btn btn-width' %>
                    <% end %>
                    </div>
                    <!-- END IMAGE FOR POST -->
                    <!-- BEGIN POST CONTENT -->
                    <div class="col s12 m9">
                      <b>Title: </b><span class="post-title-color"><%= post.title %></span><br>
                      <b>Address: </b><%= post.location.address %> <br>
                      <b>City: </b><%= link_to "#{post.location.city}", location_path(post.location.slug) %> <br>
                      <b>Post Date: </b><%= post.created_at.strftime("%B").to_s + " " + post.created_at.day.to_s + ", " + post.created_at.year.to_s %> <br>
                      <b>Experience: </b><%= post.description.slice(0, 210)+"..." %>
                      <%= link_to "Read More", post_path(post.id) %><br>
                    </div>
                    <!-- END POST CONTENT -->
                  </div>
                <hr>
              <% end %>
          <!-- END POST DATA -->
          <!-- PAGINATION -->
          <%= paginate @posts %>
          <div class="pagination_page_info">
            <%= page_entries_info @posts %>
          </div>

<!-- floating button for adding a review -->
          <div class="fixed-action-btn">
            <%= link_to new_post_path(),class: "btn-floating btn-large black" do %>
              <i class="large material-icons">add</i>
            <% end %>
          </div>

      </div>
    </div>